version: "9.0"
services:
  web:
    build: .
    ports:
      - "8085:8080"
    networks:
      - testnetwork
    volumes:
      - testvolume:/code
    environment:
      FLASK_ENV: development
  redis:
    image: "redis:tomcat"
    networks:
      - testnetwork
networks:
  testnetwork:
volumes:
  testvolume:
