pipeline {
  agent any
    stages {
      stage('BUild Application'){
        steps {
          sh 'mvn -f jenkins/java-tomcat-sample/pom.xml clean package'
       }
       post {
        success {
          echo "we are archiving the artifact"
          archiveArtifacts artifacts: '**/*.war', followSymlinks: false
        }
       }
     }
    stage('CreateTomcatImage'){
       steps {
        copyArtifacts filter: '**/*.war', fingerprintArtifacts: true, projectName: env.JOB_NAME, selector: lastSuccessful()
        echo "buiding docker images"
        sh '''
        original_pwd=$(pwd -P)
        cd jenkins/java-tomcat-sample
        docker build -t localtomcatimg:v7 .
        cd $original_pwd
        sh '''
       }
     }
     stage('deploy'){
       steps {
        echo "we are deploying the app"
        sh '''
        docker container run -itd tomcatlocalinstance -p 8083:8080 localtomcatimg:v7
    
        sh '''
       }
     }
}
}
