pipeline {
  agent any
    stages {
      stage('BUild Application'){
        steps {
          echo "we are going to build applications"
       }
     }
    stage('build'){
       steps {
        echo "we are learining build, building the code nowe"
       }
     }
     stage('deploy'){
       steps {
        echo "we are deploying the app"
       }
     }
}
}
