pipeline {
  agent any
    stages {
      stage('BUild Application'){
        steps {
          sh 'mvn -f jenkins/java-tomcat-sample/pom.xml clean package'
       }
       post {
        success {
          echo "we are archiving the artifact"
          archiveArtifacts artifacts: '**/*.war', followSymlinks: false
        }
       }
     }
    stage('CreateTomcatImage'){
       steps {
        copyArtifacts filter: '**/*.war', fingerprintArtifacts: true, projectName: env.JOB_NAME, selector: lastSuccessful()
        echo "buiding docker images"
        sh '''
        original_pwd=$(pwd -P)
        cd jenkins/java-tomcat-sample
        docker build -t localtomcatimg:$BUILD_NUMBER .
        cd $original_pwd
        sh '''
       }
     }
     stage('deploy in QA instance'){
       steps {
        echo "we are deploying the app"
        sh '''
        docker container stop localtomcatinstance || true
        docker container rm localtomcatinstance || true
        docker container run -itd --name localtomcatinstance -p 8085:8080 localtomcatimg:$BUILD_NUMBER
    
        sh '''
       }
     }
      stage('deploy in Stagig Instace'){
       steps {
         timeout(time:2, unit:'MINUTES'){
           input message: 'Approve thre staging deployment'
         }
        echo "we are deploying the app staggin enviroment"
        sh '''
        docker container stop localstaging || true
        docker container rm localstaging || true
        docker container run -itd --name localstaging -p 8084:8080 localtomcatimg:$BUILD_NUMBER
    
        sh '''
       }
     }
}
}
