---
- name: Setup WebServer
  hosts: websrvgrp
  become: yes
  tasks:
    - name: Install Apache2
      apt:
        name: apache2
        state: present
    - name: Start & Enable apache2
      service:
        name: apache2
        state: started
        enabled: yes
    - name: Copy Files
      copy:
        src: index.html
        dest: /var/www/html/index.html
- name: Setup DB server
  hosts: dbsrvgrp
  become: yes
  vars:
    dbname: group
    dbuser: devops
    dbpass: admin123
  tasks:
    - debug:
      var: dbname
    - debug:
      msg: "Value for dbname is {{dbname}}"
      
    - name: Install MySQL server
      apt:
        name: mariadb-server
        state: present
    - name: Install Python MySQL
      apt:
        name: MySQL-python
        state: present
    - name: Start & Enable mariadb service
      service:
        name: mariadb
        state: started
        enabled: yes
    - name: Create new databases with names 'devopsmysql'
      mysql_db:
        name: "{{dbname}}"
        state: present
    - name: Create database user with name 'admin'
      mysql_user:
        name: "{{dbuser}}"}
        password: "{{dbpass}}"
        priv: '*.*:ALL'
        state: present