---
- name: Provision server
  hosts: all
  become: yes
  tasks:
    - name: Install http server on Ubuntu
      apt:
        name: apache2
        state: present
      when: ansible_distribution == "Ubuntu"
    - name: Install http server on CentOS
      yum:
        name: httpd
        state: present
      when: ansible_distribution == "CentOS"

    - name: Start and Enable http service on Debian
      service:
       name: apache2
       state: started
       enabled: yes
      when: ansible_distribution == "Ubuntu"

    - name: Start and Enable http service on CentOS
      service:
       name: httpd
       state: started
       enabled: yes
      when: ansible_distribution == "CentOS"